import os
from datetime import datetime

# --- CONFIGURATION ---
BUSINESS_GOALS_FILE = "Business_Goals.md"
BRIEFINGS_DIR = "Briefings"
DASHBOARD_FILE = "Dashboard.md"

def get_files_in_folder(folder_path):
    """
    Returns a list of .md files in a specific folder.
    """
    if not os.path.exists(folder_path):
        return []
    return [f for f in os.listdir(folder_path) if f.endswith('.md')]

def read_business_goals():
    """
    Reads the content of Business_Goals.md to include in the report.
    """
    if not os.path.exists(BUSINESS_GOALS_FILE):
        return "No business goals found."
    
    with open(BUSINESS_GOALS_FILE, "r") as f:
        content = f.read()
    
    # We'll extract the main goals table or the first few lines
    return content.split("---")[0].strip()

def generate_report():
    """
    Main function to generate the CEO briefing report.
    """
    # 1. Gather data
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M:%S")
    
    done_tasks = get_files_in_folder("Done")
    pending_tasks = get_files_in_folder("Needs_Action")
    awaiting_approval = get_files_in_folder("Pending_Approval")
    
    business_goals = read_business_goals()
    
    # 2. Construct the Markdown content
    report_content = f"""# 📈 Monday Morning CEO Briefing: {date_str}

## 📝 Executive Summary
Qurrat-AI is fully operational and currently monitoring **{len(pending_tasks)}** pending actions. Business goals for Q1 are being tracked and updated.

---

## 🎯 Current Business Goals
{business_goals}

---

## 📊 Weekly Stats Snapshot
| Metric | Status | Count |
| :--- | :---: | :--- |
| **Completed This Week** | ✅ | {len(done_tasks)} |
| **Pending Tasks** | 🚨 | {len(pending_tasks)} |
| **Awaiting Approval** | ⏳ | {len(awaiting_approval)} |

---

## ✅ Completed Tasks
{chr(10).join([f"- {task}" for task in done_tasks]) if done_tasks else "- *No tasks completed this week yet.*"}

## 🚨 Needs Attention
{chr(10).join([f"- {task}" for task in pending_tasks]) if pending_tasks else "- *Inbox is clear! Great job, Syeda.*"}

---

## 💡 Message for Syeda
"Syeda, your AI Vault is thriving! We are on track for the Hackathon 0 targets. Keep up the momentum, and let's conquer the week ahead together!" 🚀✨

---
*Generated by Qurrat-AI at {time_str}*
"""
    
    # 3. Save the report to the Briefings folder
    if not os.path.exists(BRIEFINGS_DIR):
        os.makedirs(BRIEFINGS_DIR)
        
    report_filename = f"BRIEFING_{date_str}.md"
    report_path = os.path.join(BRIEFINGS_DIR, report_filename)
    
    try:
        with open(report_path, "w") as f:
            f.write(report_content)
        print(f"✅ CEO Briefing generated: {report_path}")
        
        # 4. Update Dashboard.md
        update_dashboard_with_briefing(date_str)
        
    except Exception as e:
        print(f"❌ Error generating report: {e}")

def update_dashboard_with_briefing(date_str):
    """
    Appends a note to Dashboard.md indicating that the briefing was generated.
    """
    try:
        with open(DASHBOARD_FILE, "a") as f:
            f.write(f"\n- [x] 📈 CEO Briefing generated for {date_str}\n")
        print("✅ Dashboard updated with briefing status.")
    except Exception as e:
        print(f"❌ Error updating dashboard: {e}")

if __name__ == "__main__":
    generate_report()
